// AUTO-GENERATED by scripts/gen-tray-icon.mjs — do not edit by hand.
// Placeholder menubar template glyphs (Phase A). Replaced in the design pass.
// Each state ships an @1x (18px) AND @2x (36px) rep so the status item draws on
// HiDPI menu bars (a single-scale image lays out with height 0 → invisible).
export const TRAY_ICON_IDLE_1X = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAQAAAD8x0bcAAAAPklEQVR4nGNgIAv8Z/hPSBoZEqEEizJsStCUoQtjVYbNeHIU4fINijhRiqjnJiKDgKjAxKUMCyBCCbJScgAAAEaHeX/5tfQAAAAASUVORK5CYII='
export const TRAY_ICON_IDLE_2X = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACQAAAAkCAQAAABLCVATAAAAaklEQVR4nO3USQ7AIAxDUe5/abpvRfxjGXUBZms9RUxjHJr5WgHC4iqkgREGUJQRVIcpqC6zpEKQLkKKjW1AdCeteUCTMrJ7oR8h+/hjF3LjE/nWdKMs1guObUKxr7ZLiYQYSuFEkDV3Zh7Ari3vkoDJpwAAAABJRU5ErkJggg=='
export const TRAY_ICON_RECORDING_1X = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAQAAAD8x0bcAAAAOElEQVR4nGNgIAv8Z/hPSBoZEqEEizJsStCU4VKCooxaivApgSsjShGdHU5kYBIZLURGMLJScgAA8GizTb/gp/4AAAAASUVORK5CYII='
export const TRAY_ICON_RECORDING_2X = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACQAAAAkCAQAAABLCVATAAAAV0lEQVR4nO3UOQ4AMAgDQf7/6aTPAcZygUKWfioLs6aN5QQExXlIAkMYgEKZgMowDpVlrpQIYpgjVQ1imY36UGuo3rKFUL1/xFBOIiZDAYmYGCMSEA80AR5h0UvcxmxaAAAAAElFTkSuQmCC'
